name: GitHub Actions Start With Laravel ci
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ by a ${{ github.event_name }} event, This job is now running on a ${{ runner.os }} server on  branch is ${{ github.ref }}

      - name: Check out repository code
        uses: actions/checkout@v3

       - run: php artisan test

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          
      - run: echo "ğŸ This job's status is ${{ job.status }}."
